Refactor and updates (Italian notation, support for flat chords, suppport for textScaleFactor, support for metadata)
paurakhsharma/flutter_chord pull request #12
Opened 2022-05-07 17:33 UTC by SamuMazzi

First of all, thanks for your work. I made some refactor: the code didn't seem to be very readble.
I created a new class for the transposer and added the italian notation.
I added textScaleFactor and scrollPhysics in the renderer.
I added the support for various metadata like chorus, capo, key, artist. Details are in the code. I needed these changings in my code so I've added them but if you have any doubts let me know :)

2022-05-16 00:55 UTC, paurakhsharma commented
Hey, @SamuMazzi thank you so much for this. I will review this PR shortly. Sorry for being late.

2022-05-16 03:54 UTC, paurakhsharma commented on lib/src/lyrics_renderer.dart
> +    capoStyle = widget.textStyle.copyWith(fontStyle: FontStyle.italic);
Make these configurable as well.

2022-05-16 03:55 UTC, paurakhsharma requested changes
This looks great. Just a single suggestion. Also, please add trailing commas where possible to format the code nicely.

2022-05-17 13:38 UTC, SamuMazzi commented
Did it!
I didn't find where to put trailing commas, I hope it's not a problem...

2022-05-18 07:10 UTC, SamuMazzi commented
Did it!

2022-05-18 09:33 UTC, paurakhsharma approved these changes

2022-05-18 09:33 UTC, paurakhsharma commented
Thank you so much @SamuMazzi

2022-05-18 09:33 UTC, merged