Allow external ScrollController and FIX inconsistent speed behavior
paurakhsharma/flutter_chord pull request #16
Opened 2022-10-11 14:44 UTC by eltonmorais

To give the dev more freedom to control the scroll screen I have allowed the use of a external ScrollController. It's not mandatory. If we get a null on the parameter, we use the same method as before.

I found a inconsistent behavior on the speed scroll. If I start the scroll from the top, a speed value give me a specific speed. But if I start the scroll in the midle or end of the music, then the same speed value give me a different speed.

Now same speed value allways give the same speed scrolling. What allow to create a consistent speed controller.

2022-10-11 15:09 UTC, paurakhsharma approved these changes
Looks good. Thank you so much!

2022-10-11 15:19 UTC, paurakhsharma commented
@eltonmorais Can you please fix the formatting issue and update the PR?

2022-10-19 09:29 UTC, paurakhsharma requested changes
I don't think we need to and bottom padding. That should be achievable using leading and training widgets.

2022-10-19 13:02 UTC, eltonmorais commented on lib/src/lyrics_renderer.dart
> +  final double bottomPadding;
Agree.

2022-10-19 20:49 UTC, paurakhsharma commented on lib/src/lyrics_renderer.dart
> +  final double bottomPadding;
Can you please remove them and push the changes? I will merge it after that.

2023-10-26 13:50 UTC, paurakhsharma approved these changes

2023-10-26 13:52 UTC, paurakhsharma requested changes
Please remove topPadding and bottomPadding. It can be handeled by leading and trailling widget.

2024-11-05 06:27 UTC, paurakhsharma commented
Closing because the original author didn't update the PR. Similar functionality implemented by #31

2024-11-05 06:27 UTC, closed without merging